# Generated by Django 3.2.6 on 2021-08-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiales',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
    ]
