# Generated by Django 3.2.6 on 2021-08-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20210831_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Clave'),
        ),
    ]
