# Generated by Django 3.2.6 on 2021-08-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_materiales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
