# Generated by Django 3.2.6 on 2021-08-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_materiales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='carrera',
            field=models.TextField(verbose_name='carrera'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='material',
            field=models.TextField(verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='nombre',
            field=models.TextField(verbose_name='nombre'),
        ),
    ]
