# Generated by Django 3.2.6 on 2021-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_auto_20210831_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='carrera',
            field=models.CharField(max_length=5, verbose_name='carrera'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='material',
            field=models.CharField(max_length=40, verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='nombre'),
        ),
    ]
